# File: .readthedocs.yaml

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
